name: OnCreateDispatch2
on:
   workflow_run:
     workflows: ['OnCreateDispatch']
     types: [completed]

jobs:
   on-success:
     runs-on: ubuntu-latest
     if: ${{ github.event.workflow_run.conclusion == 'success' }}
     steps:
       - shell: bash
         run: |
          expr 'CopyFolder workflow completed succesfully' > conclusionCopyFolder.txt
       - name: Upload conclusion
         uses: actions/upload-artifact@v2
         with:
           name: concCopy
           path: ./**/conclusionCopyFolder.txt    

   on-failure:
     runs-on: ubuntu-latest
     if: ${{ github.event.workflow_run.conclusion == 'failure' }}
     steps:
       - shell: bash
         run: |
          expr 'CopyFolder workflow completed with an error' > conclusionCopyFolder.txt
       - name: Upload conclusion
         uses: actions/upload-artifact@v2
         with:
           name: concCopy
           path: ./**/conclusionCopyFolder.txt


       - uses: actions/checkout@v2
         with:
           ref: temp

       - name: Invoke workflow without inputs
         uses: benc-uk/workflow-dispatch@v1
         with:
           workflow: BuildAndTestCS
           token: ${{ secrets.TOKEN }}