name: Delete
on:
  workflow_dispatch:
jobs:
  deletebranch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.TOKEN }}

      - name: Delete file 1
        run: rm -f .github/workflows/DeleteBranch.yml
        
      - name: Commit CMake change
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'action@github.com'
          git commit -am "update"
          git push    

      - name: Delete branch
        continue-on-error: true
        id: deletion
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          branches: temp
        
      - name: Deletion status
        if: steps.deletion.outcome == 'success'
        shell: bash
        run: |
          expr 'DeleteBranch workflow completed succesfully' > conclusionDeleteBranch.txt
        
      - name: Deletion status(fail)
        if: steps.deletion.outcome != 'success'
        shell: bash
        run: |
          expr 'DeleteBranch workflow completed with an error' > conclusionDeleteBranch.txt  
   
      - name: Upload conclusion
        uses: actions/upload-artifact@v2
        with:
          name: concDeleteBranch
          path: ./**/conclusionDeleteBranch.txt       
