 - name: AppendToCMake 
        if: steps.check_files2.outputs.files_exists == 'true' 
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: CMakeLists.txt
          contents: |
            add_subdirectory(CPPTests)
          write-mode: append      
      - name: Commit CMake change
        if: steps.check_files2.outputs.files_exists == 'true'
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'action@github.com'
          git commit -am "update CMake"
          git push  
     
          
      - name: Install gtest manually
        id: cpp_s1
        if: steps.check_files2.outputs.files_exists == 'true'
        run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && ls -l lib && sudo cp lib/*.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
      - uses: actions/checkout@v2
        with:
          ref: temp
      - name: configure
        id: cpp_s2
        if: steps.check_files2.outputs.files_exists == 'true'
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..
      - name: make
        id: cpp_s3
        if: steps.check_files2.outputs.files_exists == 'true'
        run: cd build && make
      - name: Run Test
        continue-on-error: true
        id: cpp_s4
        if: steps.check_files2.outputs.files_exists == 'true'
        run: /home/runner/work/GitHubActionsTest-2/GitHubActionsTest-2/build/CPPTests/GitHubActionsTest-2.test 
