name: Check BuildAndTest workflow
on:
   workflow_run:
     workflows: ['BuildAndTest']
     types: [completed]

jobs:
   on-success:
     runs-on: ubuntu-latest
     if: ${{ github.event.workflow_run.conclusion == 'success' }}
     steps:
       - shell: bash
         run: |
          expr 'BuildAndTest workflow completed succesfully' > conclusionBuildAndTest.txt
       - name: Upload conclusion
         uses: actions/upload-artifact@v2
         with:
           name: concBuildAndTest
           path: ./**/conclusionBuildAndTest.txt    

   on-failure:
     runs-on: ubuntu-latest
     if: ${{ github.event.workflow_run.conclusion == 'failure' }}
     steps:
       - shell: bash
         run: |
          expr 'BuildAndTest workflow completed with an error' > conclusionBuildAndTest.txt
       - name: Upload conclusion
         uses: actions/upload-artifact@v2
         with:
           name: concBuildAndTest
           path: ./**/conclusionBuildAndTest.txt