name: Copy
on:
  workflow_run:
    workflows: ['OnCreate']                    
    types:
      - completed
  workflow_dispatch:    
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: temp
        
    - name: Check file existence1
      id: check_files1
      uses: andstor/file-existence-action@v1.1.0
      with:
        files: "**/*.csproj"
        
    - name: Check file existence2
      id: check_files2
      uses: andstor/file-existence-action@v1.1.0
      with:
        files: "**/*.cpp"    
        
    - uses: actions/checkout@v2
      with:
        ref: main    
    - name: Copycat1
      if: steps.check_files1.outputs.files_exists == 'true' 
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.TOKEN }}
        src_path: /tests/.
        dst_path: /.
        dst_owner: IlMkn
        dst_repo_name: GitHubActionsTest-2
        dst_branch: temp
        src_branch: main
        
    - name: Copycat2
      if: steps.check_files2.outputs.files_exists == 'true' 
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.TOKEN }}
        src_path: /test/.
        dst_path: /test/.
        dst_owner: IlMkn
        dst_repo_name: GitHubActionsTest-2
        dst_branch: temp
        src_branch: main   
     
    - name: Checkout 
      if: steps.check_files2.outputs.files_exists == 'true' 
      uses: actions/checkout@v2
      with:
        ref: temp  
        
    - name: AppendToCMake 
      if: steps.check_files2.outputs.files_exists == 'true' 
      uses: DamianReeves/write-file-action@v1.0
      with:
        path: ${{ env.home}}/.txt
        contents: |
          echo "add_subdirectory(test)"
        write-mode: append    
