name: DeleteBranch
on:
  workflow_run:
    workflows: ['BuildAndTest']                    
    types:
      - completed
  workflow_dispatch:
jobs:
  deletebranch:
    runs-on: ubuntu-latest
    steps:        
    - uses: actions/checkout@v2
    - name: Delete branch
      uses: dawidd6/action-delete-branch@v3
      with:
        github_token: ${{github.token}}
        branches: temp2
