name: 'Test Report'
on:
  workflow_run:
    workflows: ['BuildAndTest']                    
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1.5.0
      with:
        artifact: test-results            
        name: dotnet-trx                  
        path: ./**/TestResults/*.trx                   
        reporter: dotnet-trx   
  deletebranch:
    runs-on: ubuntu-latest
    steps:         
    - name: Delete branch
      uses: dawidd6/action-delete-branch@v3
      with:
        github_token: ${{github.token}}
        branches: temp
