name: Delete
on: [workflow_dispatch]
jobs:
  deletebranch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Delete file 
        run: rm -f .github/workflows/DeleteBranch.yml
